version: "2"

services:
  app:
    build:
      context: .
    entrypoint:
      - /go/bin/oauth-server-demo
      - -db-user=oauthsvr
      - -db-password=oauthsvr
      - -db-name=oauthsvr
      - -db-addr=db:3306
      - -redis-addr=redis:6379
      - -access-expiration=3600 # access tokens expiration time in seconds
      - -secret=you-really-need-to-change-this
    ports:
      - "8080:8080"
  db:
    image: mysql:5.7.12
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=oauthsvr
      - MYSQL_USER=oauthsvr
      - MYSQL_PASSWORD=oauthsvr
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - "8888:80"
  redis:
    image: redis:alpine